name: "Deploy FlickrImageFinder"

on:
  push:
    branches: ["master"]
env:
  PROJECT_PATH: FlickrImageFinder/FlickrImageFinder.csproj
  UT_PROJECT_PATH: FlickrImageFinder.Tests/FlickrImageFinder.Tests.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x

      - uses: actions/restore-dependencies@v2
      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - uses: actions/build-release@v2
      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
      
      - uses: actions/test-release@v2
      - run: dotnet test ${{ env.UT_PROJECT_PATH }} -c Release --verbosity normal

      - uses: actions/publish-release@v2
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v2.0.1"
          release_name: ${{ github.ref }}

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: FlickrImageFinder/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
