name: "Deploy FlickrImageFinder"

on:
  push:
    branches: ["master"]
env:
  PROJECT_PATH: FlickrImageFinder/FlickrImageFinder.csproj

jobs:      
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup FlickrImageFinder
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - uses: actions/checkout@v2
      - name: Restore Dependencies
      - uses: actions/setup-dotnet@v1
      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - uses: actions/checkout@v2
      - name: Build Release Binaries
      - uses: actions/setup-dotnet@v1
      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
      
      - uses: actions/checkout@v2
      - name: Run Unit Tests
      - uses: actions/setup-dotnet@v1
      -  run: dotnet test --no-build --verbosity normal

      - uses: actions/checkout@v2
      - name: Publish Packages
      - uses: actions/setup-dotnet@v1
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: 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
        with:
          tag_name: "1.0"
          release_name: ${{ github.ref }}

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: FlickrImageFinder/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
